# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BinaryThresh.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Binary_thresh_Dialog(object):
    def setupUi(self, Binary_thresh_Dialog):
        Binary_thresh_Dialog.setObjectName("Binary_thresh_Dialog")
        Binary_thresh_Dialog.resize(1179, 487)
        self.sat_im_graphicsView = QtWidgets.QGraphicsView(Binary_thresh_Dialog)
        self.sat_im_graphicsView.setGeometry(QtCore.QRect(10, 40, 491, 341))
        self.sat_im_graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.sat_im_graphicsView.setMouseTracking(False)
        self.sat_im_graphicsView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sat_im_graphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.sat_im_graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.sat_im_graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.sat_im_graphicsView.setObjectName("sat_im_graphicsView")
        self.sat_label = QtWidgets.QLabel(Binary_thresh_Dialog)
        self.sat_label.setGeometry(QtCore.QRect(10, 20, 102, 17))
        self.sat_label.setObjectName("sat_label")
        self.cctv_im_graphicsView = QtWidgets.QGraphicsView(Binary_thresh_Dialog)
        self.cctv_im_graphicsView.setGeometry(QtCore.QRect(530, 40, 491, 341))
        self.cctv_im_graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.cctv_im_graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.cctv_im_graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.cctv_im_graphicsView.setObjectName("cctv_im_graphicsView")
        self.cctv_label = QtWidgets.QLabel(Binary_thresh_Dialog)
        self.cctv_label.setGeometry(QtCore.QRect(530, 20, 73, 17))
        self.cctv_label.setObjectName("cctv_label")
        self.validate_buttonBox = QtWidgets.QDialogButtonBox(Binary_thresh_Dialog)
        self.validate_buttonBox.setGeometry(QtCore.QRect(1040, 40, 80, 25))
        self.validate_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.validate_buttonBox.setObjectName("validate_buttonBox")
        self.sat_thresh_horizontalSlider = QtWidgets.QSlider(Binary_thresh_Dialog)
        self.sat_thresh_horizontalSlider.setGeometry(QtCore.QRect(150, 430, 160, 16))
        self.sat_thresh_horizontalSlider.setMaximum(255)
        self.sat_thresh_horizontalSlider.setProperty("value", 180)
        self.sat_thresh_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sat_thresh_horizontalSlider.setObjectName("sat_thresh_horizontalSlider")
        self.sat_label_2 = QtWidgets.QLabel(Binary_thresh_Dialog)
        self.sat_label_2.setGeometry(QtCore.QRect(170, 400, 125, 17))
        self.sat_label_2.setObjectName("sat_label_2")
        self.sat_thresh_lineEdit = QtWidgets.QLineEdit(Binary_thresh_Dialog)
        self.sat_thresh_lineEdit.setGeometry(QtCore.QRect(200, 450, 61, 25))
        self.sat_thresh_lineEdit.setObjectName("sat_thresh_lineEdit")
        self.cctv_thresh_lineEdit = QtWidgets.QLineEdit(Binary_thresh_Dialog)
        self.cctv_thresh_lineEdit.setGeometry(QtCore.QRect(750, 450, 61, 25))
        self.cctv_thresh_lineEdit.setObjectName("cctv_thresh_lineEdit")
        self.sat_label_3 = QtWidgets.QLabel(Binary_thresh_Dialog)
        self.sat_label_3.setGeometry(QtCore.QRect(730, 400, 125, 17))
        self.sat_label_3.setObjectName("sat_label_3")
        self.cctv_thresh_horizontalSlider = QtWidgets.QSlider(Binary_thresh_Dialog)
        self.cctv_thresh_horizontalSlider.setGeometry(QtCore.QRect(700, 430, 160, 16))
        self.cctv_thresh_horizontalSlider.setMaximum(255)
        self.cctv_thresh_horizontalSlider.setProperty("value", 180)
        self.cctv_thresh_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cctv_thresh_horizontalSlider.setObjectName("cctv_thresh_horizontalSlider")
        self.cctv_label_2 = QtWidgets.QLabel(Binary_thresh_Dialog)
        self.cctv_label_2.setGeometry(QtCore.QRect(1030, 100, 97, 17))
        self.cctv_label_2.setObjectName("cctv_label_2")
        self.widget = QtWidgets.QWidget(Binary_thresh_Dialog)
        self.widget.setGeometry(QtCore.QRect(1030, 130, 141, 83))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.denoise_cctv_checkBox = QtWidgets.QCheckBox(self.widget)
        self.denoise_cctv_checkBox.setChecked(True)
        self.denoise_cctv_checkBox.setObjectName("denoise_cctv_checkBox")
        self.verticalLayout.addWidget(self.denoise_cctv_checkBox)
        self.denoise_sat_checkBox = QtWidgets.QCheckBox(self.widget)
        self.denoise_sat_checkBox.setChecked(True)
        self.denoise_sat_checkBox.setObjectName("denoise_sat_checkBox")
        self.verticalLayout.addWidget(self.denoise_sat_checkBox)
        self.align_color_checkBox = QtWidgets.QCheckBox(self.widget)
        self.align_color_checkBox.setChecked(True)
        self.align_color_checkBox.setObjectName("align_color_checkBox")
        self.verticalLayout.addWidget(self.align_color_checkBox)

        self.retranslateUi(Binary_thresh_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Binary_thresh_Dialog)

    def retranslateUi(self, Binary_thresh_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Binary_thresh_Dialog.setWindowTitle(_translate("Binary_thresh_Dialog", "binary threshold selection"))
        self.sat_label.setText(_translate("Binary_thresh_Dialog", "Satellite image"))
        self.cctv_label.setText(_translate("Binary_thresh_Dialog", "cctv image"))
        self.sat_label_2.setText(_translate("Binary_thresh_Dialog", "threshold satellite"))
        self.sat_thresh_lineEdit.setText(_translate("Binary_thresh_Dialog", "180"))
        self.cctv_thresh_lineEdit.setText(_translate("Binary_thresh_Dialog", "180"))
        self.sat_label_3.setText(_translate("Binary_thresh_Dialog", "threshold cctv"))
        self.cctv_label_2.setText(_translate("Binary_thresh_Dialog", "Preprocessing"))
        self.denoise_cctv_checkBox.setText(_translate("Binary_thresh_Dialog", "Denoise cctv"))
        self.denoise_sat_checkBox.setText(_translate("Binary_thresh_Dialog", "Denoise satellite"))
        self.align_color_checkBox.setText(_translate("Binary_thresh_Dialog", "Align color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Binary_thresh_Dialog = QtWidgets.QDialog()
    ui = Ui_Binary_thresh_Dialog()
    ui.setupUi(Binary_thresh_Dialog)
    Binary_thresh_Dialog.show()
    sys.exit(app.exec_())
